version: "3.8"
services:
  database:
    container_name: database
    build:
      context: /src/main/resources/init-sql/
    environment:
      MYSQL_DATABASE: beermachine
    ports:
      - "3306:3306"